export JAVA_HOME=/home/disk4/zhangstar/baidu/bdg/doris/palo-toolchain/jdk1.8.0_131
# export JAVA_HOME=/home/disk4/zhangstar/jdk-11.0.1
export CUSTOM_MAVEN_REPO=http://maven.scm.baidu.com:8081/nexus/content/groups/public
export PATH=/home/disk4/zhangstar/baidu/bdg/doris/palo-toolchain/apache-maven-3.5.4/bin/:/home/disk4/zhangstar/baidu/bdg/doris/palo-toolchain/jdk1.8.0_131/bin/:/home/disk4/zhangstar/baidu/bdg/doris/palo-toolchain/ldb_toolchain/bin:/home/disk4/zhangstar/.BCloud/bin:/home/disk4/zhangstar/.jumbo/bin:/opt/compiler/gcc-10/bin:/usr/lib64/qt-3.3/bin:/usr/kerberos/sbin:/usr/kerberos/bin:/usr/local/bin:/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/sbin:/opt/bin:/home/opt/bin:/home/disk4/zhangstar/bin
export DORIS_POST_BUILD_HOOK=/home/disk4/zhangstar/baidu/bdg/doris/post-build-hook.sh
export REPOSITORY_URL=http://bjhw-palo-sandbox-palo00.bjhw.baidu.com:8080/download/palo-thirdparty-repository
export PATCH_COMPILER_RT=true
export CUSTOM_NPM_REGISTRY=http://registry.npm.baidu-int.com/
export WITH_MYSQL=ON
export WITH_LZO=ON
export CUSTOM_UI_DIST=/home/disk4/zhangstar/baidu/bdg/doris/cdw-ui/dist
#export DORIS_GCC_HOME=/opt/compiler/gcc-10
export ASAN_SYMBOLIZER_PATH=/home/disk4/zhangstar/baidu/bdg/doris/palo-toolchain/ldb_toolchain/bin/llvm-symbolizer
export USE_LLD=ON
export BUILD_DOCS=OFF
export BUILD_META_TOOL=OFF
export DORIS_TOOLCHAIN=gcc #clang gcc  --clean !!!
export BUILD_TYPE=Debug #Release ASAN Debug
# export LD_LIBRARY_PATH=/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.275.b01-0.el6_10.x86_64/jre/lib/amd64/server/:$LD_LIBRARY_PATH
# export LD_LIBRARY_PATH=/home/disk4/zhangstar/jdk8u242-b08/jre/lib/amd64/server:$LD_LIBRARY_PATH
# export LD_LIBRARY_PATH=/home/disk4/zhangstar/jdk-11.0.1/lib/server/
export LD_LIBRARY_PATH=/home/disk4/zhangstar/baidu/bdg/doris/palo-toolchain/jdk1.8.0_131/jre/lib/amd64/server
export LIBJVM_PATH=/home/disk4/zhangstar/baidu/bdg/doris/palo-toolchain/jdk1.8.0_131/jre/lib/amd64/server